-- tables .
CREATE TABLE DIAGRAMA (
    ID_DIAGRAMA NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(100),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    CONSTRAINT PK_DIAGRAMA PRIMARY KEY (ID_DIAGRAMA)
);

CREATE TABLE CLASE_UML (
    ID_CLASE NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_DIAGRAMA NUMBER,
    NOMBRE VARCHAR2(100),
    CONSTRAINT PK_CLASE PRIMARY KEY (ID_CLASE),
    CONSTRAINT FK_CLASE_DIAGRAMA FOREIGN KEY (ID_DIAGRAMA)
        REFERENCES DIAGRAMA(ID_DIAGRAMA)
);

CREATE TABLE ATRIBUTO_UML (
    ID_ATRIBUTO NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_CLASE NUMBER,
    NOMBRE VARCHAR2(100),
    TIPO VARCHAR2(50),
    CONSTRAINT PK_ATRIBUTO PRIMARY KEY (ID_ATRIBUTO)
);

CREATE TABLE METODO_UML (
    ID_METODO NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_CLASE NUMBER,
    NOMBRE VARCHAR2(100),
    RETORNO VARCHAR2(50),
    CONSTRAINT PK_METODO PRIMARY KEY (ID_METODO)
);

COMMIT;
-- store procedure .
CREATE OR REPLACE PROCEDURE SP_GUARDAR_CLASE (
    P_ID_DIAGRAMA IN NUMBER,
    P_NOMBRE_CLASE IN VARCHAR2
) AS
BEGIN
    INSERT INTO CLASE_UML (ID_DIAGRAMA, NOMBRE)
    VALUES (P_ID_DIAGRAMA, P_NOMBRE_CLASE);
END;
/

COMMIT;

-- diagrama .
INSERT INTO DIAGRAMA (NOMBRE) VALUES ('Diagrama Principal');

COMMIT;

SELECT * FROM DIAGRAMA;
